server:
  port: 8444
  
spring:
  datasource:
# -------------MSSQL------------- 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=downloadexcel;TrustServerCertificate=True;encrypt=true;
    username: sa    
    password: "0000"
# -------------MYSQL------------- 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/education
#    username: root
#    password: sasa
    
    
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#          '[format_sql]': true