server:
  port: 8444
  servlet:
    context-path: /downloadFile
    encoding:
      charset: UTF-8
  
spring:
  datasource:
# -------------MSSQL------------- 
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=downloadexcel;TrustServerCertificate=True;encrypt=true;
#    username: sa    
#    password: "0000"
# -------------MYSQL------------- 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education
    username: root
    password: sasa
    
    
#  jpa:
## -------------JPA------------- 
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#      dialect: org.hibernate.dialect.MySQL8Dialect  # 或 org.hibernate.dialect.SQLServerDialect
#      format_sql: true
#